//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVShowsNetworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TVshow
    {
        public int ShowID { get; set; }
        [Display(Name = "Network")]
        public int NetworkID { get; set; }
        public string Title { get; set; }
        [Display(Name = "Length (minutes)")]
        public Nullable<int> Length { get; set; }
        public string Genre { get; set; }
    
        public virtual TVnetwork TVnetwork { get; set; }
    }
}
